version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: herderhub-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: signup
      MYSQL_USER: herderhubuser
      MYSQL_PASSWORD: AmirShahid2024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
