version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: herderhub-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Amir@2024#
      MYSQL_DATABASE: signup
     
      MYSQL_PASSWORD: Amir@2024#
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
