# Use official MySQL image from Docker Hub
FROM mysql:8.0

# Set environment variables for MySQL root password and default database
ENV MYSQL_ROOT_PASSWORD=my-secret-pw
ENV MYSQL_DATABASE=signup
ENV MYSQL_USER=herderhubuser
ENV MYSQL_PASSWORD=Amir2024

# Expose port 3306 for MySQL connections
EXPOSE 3306
